### PR TITLE
fix use get_model on django 1.9+

### PR DESCRIPTION
**Pull request by tarvitz**
Django 1.9+ won't have anymore get_model, use AppConfig
based interfaces instead

### CODE REVIEW

**Comment by Fantomas42** [comment]
Thanks, this is fixed in https://github.com/Fantomas42/django-tagging/commit/697c05620ea5078d6dc052f15e2964c4b6a94274

No needs to compat module, because tagging support from Django 1.7 and the app.get_model method is present in this version of Django.

**Comment by tarvitz** [comment]
NP, your fix is better I agree there's no need to make compat as django.apps exists in django-1.7.
Made my fix fast, not pretty proper though :)

**Comment by evenicoulddoit** [comment]
I was about to make a PR exactly matching 697c056, also looked at 948a193 and thought that it was the wrong decision given your support of 1.7+ and noting that apps.get_model is present since. Good job both, can we bump the version so that we can use this?

**Comment by thecardcheat** [comment]
+1 release thanks!

**Pull request closed without merging**
